### ISSUE TITLE
Component build

### ISSUE THREAD

**Issue by glennreyes** [wvidigital/WVUnited-React-UI-Components#7]
Currently we are building with webpack and every component into one `dist/ui.js`. This means, for example if there's one place where we want to import only `<Heading />`, we would import the entire bundle including `slick-carousel`, etc. (Needs tree-shaking to remove unused code)

Ideally, this can be avoided.

Current output when running the build:

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  ui.js (1.71 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (1.71 MiB)
      ui.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

**Comment by rradoychev** [comment]
I have suggestions for overall improvement, next week we will speak about it and figure it all out.

Greetings!

**Comment by glennreyes** [comment]
As discussed with @rradoychev, I'd propose to switch to rollup which is more suitable for component libs.
